# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-14 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WikiTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('url', models.URLField(verbose_name='url')),
                ('description', models.TextField(verbose_name='description')),
            ],
        ),
    ]
