# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-14 13:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('wikiviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiPageviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='year')),
                ('project', models.CharField(max_length=30, verbose_name='project/site')),
                ('agent', models.CharField(max_length=10, verbose_name='agent')),
                ('access', models.CharField(max_length=10, verbose_name='access')),
                ('count', models.IntegerField(verbose_name='count')),
                ('per_yearday', models.CharField(max_length=4096, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='per year-day')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wikiviews.WikiTerm', verbose_name='term')),
            ],
        ),
    ]
