# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 22:55
from __future__ import unicode_literals

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wikiviews', '0002_wikipageviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickleCache',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='created on')),
                ('data', picklefield.fields.PickledObjectField(blank=True, default=None, editable=False, null=True, verbose_name='headers')),
            ],
        ),
    ]
